-- AddColumn
ALTER TABLE "Power" ADD COLUMN "mpCost" INTEGER DEFAULT 0,
ADD COLUMN "sanityCost" INTEGER DEFAULT 0,
ADD COLUMN "hpCost" INTEGER DEFAULT 0;

-- AddColumn
ALTER TABLE "RollHistory" ADD COLUMN "mpSpent" INTEGER,
ADD COLUMN "sanitySpent" INTEGER,
ADD COLUMN "hpSpent" INTEGER;
